install:
  # g++ # MinGW 32-bit 5.3.0
  - set PATH=%PATH%;C:\MinGW\bin
  # qmake
  #- set QTDIR=C:\Qt\5.5\mingw492_32
  - set QTDIR=C:\Qt\5.8\mingw53_32
  - set PATH=%PATH%;%QTDIR%\bin
  # Boost
  - set PATH=%PATH%;C:\Libraries\boost_1_63_0

build_script:
  # Diagnostics
  - g++ -v
  # Build prerequisites
  - cd ..
  - git clone https://github.com/richelbilderbeek/RibiClasses
  - git clone https://github.com/Microsoft/GSL
  - dir
  - cd Maziak
  # Console test
  - qmake -qt=qt5 MaziakConsoleTest.pro
  - mingw32-make debug
  - MaziakConsoleTest.exe
  # Console
  - qmake MaziakConsole.pro
  - mingw32-make debug
  - MaziakConsole.exe --about
  # Desktop test
  - qmake MaziakDesktopTest.pro
  - mingw32-make debug
  - MaziakDesktopTest.exe
  # Desktop
  - qmake MaziakDesktop.pro
  - mingw32-make release
  - MaziakDesktop.exe --profile
