sudo: require
language: cpp
compiler: gcc
dist: trusty # Qt5, from https://gist.github.com/jreese/6207161#gistcomment-1462109

addons: 
  apt: 
    packages: libboost-all-dev

before_install:
  # Qt5, from https://gist.github.com/jreese/6207161#gistcomment-1462109
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # Qt5
  - sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
  # C++14
  - sudo apt-get install -qq g++-5
  # Codecov
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90
  - sudo pip install codecov
  # OCLint
  - ./install_oclint
  # Other GitHubs
  - ./download_other_githubs

# Start virtual X server, from https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: 
  # Console test
  - qmake -qt=qt5 MaziakConsoleTest.pro
  - make debug
  - ./MaziakConsoleTest
  # Console
  - qmake -qt=qt5 MaziakConsole.pro
  - make debug
  # Do not do below: Travis will not be able to handle this
  # - ./MaziakConsole & 
  # Desktop debug profile run
  - qmake -qt=qt5 MaziakDesktopTest.pro
  - make debug
  - ./MaziakDesktopTest
  # Desktop debug profile run
  - make clean
  - qmake -qt=qt5 MaziakDesktop.pro
  - make debug
  - ./MaziakDesktop --profile
  - gprof MaziakDesktop > gprof.log
  - head gprof.log -n 1000
  # Get code coverage
  - ./get_code_cov
  - codecov
  # Desktop release profile run
  - make clean
  - qmake -qt=qt5 MaziakDesktop.pro
  - make release
  - ./MaziakDesktop --profile
  - gprof MaziakDesktop > gprof.log
  - head gprof.log -n 1000
  # Call OCLint
  - ./do_oclint

after_success:
  - bash <(curl -s https://codecov.io/bash)