language: cpp
dist: bionic
compiler:
  - gcc
  # - clang 

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default
  # cppcheck
  - sudo apt-get install -qq cppcheck
  # Codecov
  - sudo pip install codecov
  # OCLint
  - ./install_oclint
  # Other GitHubs
  - ./download_other_githubs

services:
 - xvfb

script: 
  # Console test
  - qmake -qt=qt5 MaziakConsoleTest.pro
  - make --silent debug
  - ./MaziakConsoleTest
  # Console
  - qmake -qt=qt5 MaziakConsole.pro
  - make --silent debug
  # Do not do below: Travis will not be able to handle this
  # - ./MaziakConsole & 
  # Desktop debug run
  - qmake -qt=qt5 MaziakDesktopQtTest.pro
  - make --silent debug
  - ./MaziakDesktopQtTest
  # Desktop debug profile run
  - qmake -qt=qt5 MaziakDesktopQt.pro
  - make --silent debug
  - ./MaziakDesktopQt --profile
  # Get code coverage
  - ./get_code_cov >/dev/null
  - codecov >/dev/null
  # Desktop release profile run
  - make clean
  - qmake -qt=qt5 MaziakDesktopQt.pro
  - make --silent release
  - time ./MaziakDesktopQt --profile
  - gprof MaziakDesktopQt > gprof.log
  - head gprof.log -n 100
  # cppcheck
  - cppcheck --quiet --error-exitcode=1 . 
  # Call OCLint
  - ./do_oclint

after_success:
  - bash <(curl -s https://codecov.io/bash)
